apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: mostafaewida/fixed_backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8000
          initialDelaySeconds: 30  # Wait 30 seconds before first check
          periodSeconds: 10        # Check every 10 seconds
          timeoutSeconds: 3        # Timeout after 3 seconds
          failureThreshold: 3      # Mark as failed after 3 consecutive failures    
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8000
          initialDelaySeconds: 5   # Wait 5 seconds before first check
          periodSeconds: 5        # Check every 5 seconds
          timeoutSeconds: 2       # Timeout after 2 seconds
          successThreshold: 1     # 1 successful check = ready
          failureThreshold: 3     # Mark as not ready after 3 failures