version: '3.8'

services:
  backend:
    image: mostafaewida/fixed_backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://lclr_user:1th4ok1ymfurQaM9@backend-database-primary:27017/lclr_db
      - REDIS_URL=redis://:hgdfwegf67435jsdbjkTY@redis:6379
      - RABBITMQ_URL=amqp://bugs-bunny:sdfjgh45iotgdfjk456@rabbitmq:5672
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=7eg35sJFHE366dgwfIQueuiKDJ837473KSOWEIhffhrWDbdjh
      - KEYCLOAK_CLIENT_ID=travel-api
      - KEYCLOAK_REALM=travel-realm
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=minio-root
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
    depends_on:
      - redis
      - rabbitmq
      - keycloak
      - minio
      - apm-server

  frontend:
    image: mostafaewida/fixed_frontend  
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_KEYCLOAK_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_REALM=travel-realm
      - REACT_APP_KEYCLOAK_CLIENT_ID=travel-api
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass hgdfwegf67435jsdbjkTY
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: bugs-bunny
      RABBITMQ_DEFAULT_PASS: sdfjgh45iotgdfjk456
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 7eg35sJFHE366dgwfIQueuiKDJ837473KSOWEIhffhrWDbdjh
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio-root
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.9.0
    ports:
      - "8200:8200"
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  redis_data:
  postgres_data:
  minio_data:
  rabbitmq_data:
  es_data: