apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-booking-logging
  annotations:
    # nginx.ingress.kubernetes.io/whitelist-source-range: "156.203.137.184, 10.0.0.0/16"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - elastic.travel-booking.com
    - kibana.travel-booking.com
    secretName: travel-booking-wildcard-tls
  rules:
  - host: elastic.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-master
            port:
              number: 9200
  
  - host: kibana.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kibaana-kibana
            port:
              number: 5601


  - host: apm.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apm-server-apm-server
            port:
              number: 8200

