apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-booking-auth
  annotations:
    # nginx.ingress.kubernetes.io/whitelist-source-range: "156.203.137.184, 10.0.0.0/16"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - auth.travel-booking.com
    secretName: travel-booking-wildcard-tls
  rules:
  - host: auth.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080