apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-booking-public
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - travel-booking.com
    - app.travel-booking.com
    - api.travel-booking.com
    secretName: travel-booking-wildcard-tls
  rules:
  - host: travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  
  - host: app.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  
  - host: api.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000