apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-booking-monitoring
  annotations:
    # nginx.ingress.kubernetes.io/whitelist-source-range: "156.203.137.184, 10.0.0.0/16"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - monitor.travel-booking.com
    - grafana.travel-booking.com
    secretName: travel-booking-wildcard-tls
  rules:
  - host: monitor.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              number: 9090
  
  - host: grafana.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000