apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-booking-public
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - beans.travel-booking.com
    secretName: travel-booking-wildcard-tls
  rules:


  - host: beans.travel-booking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opbeans-java
            port:
              number: 8000
