apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  REACT_APP_API_BASE_URL: "http://backend.fullstack-app.svc.cluster.local:8000"
  REACT_APP_KEYCLOAK_URL: "http://keycloak-http.fullstack-app.svc.cluster.local:8080/auth"
  REACT_APP_KEYCLOAK_REALM: "myrealm"
  REACT_APP_KEYCLOAK_CLIENT_ID: "frontend"
  REACT_APP_ENVIRONMENT: "production"


  NGINX_CONF: |
          server {
            listen 80;
            server_name localhost;
            
            location / {
                try_files $uri $uri/ /index.html;
            }
            
            location /api {
                proxy_pass https;//wordpress.wtfix.com;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /healthz {
                return 200 'healthy';
                add_header Content-Type text/plain;
            }
          }