apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
data:
  config.js: |
          const config = {
            REACT_APP_API_URL: "https://laughing-barnacle-9wgvr7q75qj3p7p9-8000.app.github.dev",
          };

          export default config;


  NGINX_CONF: |
          server {
            listen 80;
            server_name localhost;
            
            location / {
                try_files $uri $uri/ /index.html;
            }
            
            location /api {
                proxy_pass https;//wordpress.wtfix.com;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /healthz {
                return 200 'healthy';
                add_header Content-Type text/plain;
            }
          }