apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-app
  namespace: mostafa
spec:
  dnsNames:
    - wordpress.wtfix.com
  secretName: wordpress-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer